model_list:

  - model_name: groq/*
    litellm_params:
      model: groq/*
      api_base: "https://groqpr.vercel.app/groq/openai/v1"
      api_key: os.environ/GROQ_API_KEY
      ##api_version: "2023-05-15"
      rpm: 480
      rpm: 33
      #timeout: 100
      #stream_timeout: 60
      input_cost_per_token: 0.01
      output_cost_per_token: 0.01
      input_cost_per_second: 0.000420
      #top_p: 0
      timeout: 1
      stream_timeout: 1
      max_retries: 2
      #api_version: "2023-05-15"
  
  - model_name: groq/*
    litellm_params:
      model: groq/*
      api_base: "https://groqpr.vercel.app/groq/openai/v1"
      api_key: os.environ/GROQ_API_KEY2
      ##api_version: "2023-05-15"
      rpm: 480
      rpm: 33
      #timeout: 100
      #stream_timeout: 60
      input_cost_per_token: 0.01
      output_cost_per_token: 0.01
      input_cost_per_second: 0.000420
      #top_p: 0
      timeout: 1
      stream_timeout: 1
      max_retries: 2
      #api_version: "2023-05-15"  

  - model_name: groq/*
    litellm_params:
      model: groq/*
      api_base: "https://groqpr.vercel.app/groq/openai/v1"
      api_key: os.environ/GROQ_API_KEY3
      ##api_version: "2023-05-15"
      rpm: 480
      rpm: 33
      #timeout: 100
      #stream_timeout: 60
      input_cost_per_token: 0.01
      output_cost_per_token: 0.01
      input_cost_per_second: 0.000420
      #top_p: 0
      timeout: 1
      stream_timeout: 1
      max_retries: 2
      #api_version: "2023-05-15"

  - model_name: groq/*
    litellm_params:
      model: groq/*
      api_base: "https://groqpr.vercel.app/groq/openai/v1"
      api_key: os.environ/GROQ_API_KEY4
      ##api_version: "2023-05-15"
      rpm: 480
      rpm: 33
      #timeout: 100
      #stream_timeout: 60
      input_cost_per_token: 0.01
      output_cost_per_token: 0.01
      input_cost_per_second: 0.000420
      #top_p: 0
      timeout: 1
      stream_timeout: 1
      max_retries: 2
      #api_version: "2023-05-15"

  - model_name: mistral/*
    litellm_params:
      model: mistral/*
      api_base: "https://api.mistral.ai/v1"
      api_key: os.environ/MISTRAL_API_KEY
      input_cost_per_second: 0.000420
      ##api_version: "2023-05-15"
      rpm: 480
      max_tokens: 8191
      max_input_tokens: 32000
      max_output_tokens: 8191
      input_cost_per_token: 0.00000025
      output_cost_per_token: 0.00000025
      litellm_provider: "mistral"
      mode: "chat"
      supports_assistant_prefill: true
      rpm: 33
      #timeout: 100
      #stream_timeout: 60
      timeout: 1
      stream_timeout: 1
      max_retries: 2
      #api_version: "2023-05-15"
  
  - model_name: emb
    litellm_params:
      model: mistral/mistral-embed
      api_base: "https://api.mistral.ai/v1"
      api_key: os.environ/MISTRAL_API_KEY
      input_cost_per_token: 0.01
      output_cost_per_token: 0.01
      input_cost_per_second: 0.000420
      ##api_version: "2023-05-15"
      rpm: 480
      rpm: 33
      #timeout: 100
      #stream_timeout: 60

  - model_name: embedding
    litellm_params:
      model: openai/text-embedding-3-large
      api_base: "https://groqpr.vercel.app/openai/v1"
      api_key: os.environ/OPENAI_API_KEY
      input_cost_per_token: 0.01
      output_cost_per_token: 0.01
      input_cost_per_second: 0.000420
      ##api_version: "2023-05-15"
      rpm: 480
      rpm: 33
      #timeout: 100
      #stream_timeout: 60

  - model_name: embedding
    litellm_params:
      model: openai/text-embedding-ada-002
      api_base: "https://groqpr.vercel.app/openai/v1"
      api_key: os.environ/OPENAI_API_KEY
      input_cost_per_token: 0.01
      output_cost_per_token: 0.01
      input_cost_per_second: 0.000420
      ##api_version: "2023-05-15"
      rpm: 480
      rpm: 33
      #timeout: 100
      #stream_timeout: 60



  #- model_name: "*"
  #  litellm_params:
  #    model: mistral/*
  #    api_base: "https://api.mistral.ai/v1"
  #    api_key: os.environ/MISTRAL_API_KEY
  #    input_cost_per_token: 0.01
  #    output_cost_per_token: 0.01
  #    input_cost_per_second: 0.000420
  #    timeout: 1
  #    stream_timeout: 1
  #    max_retries: 2
  #    rpm: 480
#
  #- model_name: "*"
  #  litellm_params:
  #    model: groq/*
  #    api_base: "https://groqpr.vercel.app/groq/openai/v1"
  #    api_key: os.environ/GROQ_API_KEY
  #    input_cost_per_token: 0.01
  #    output_cost_per_token: 0.01
  #    input_cost_per_second: 0.000420
  #    timeout: 1
  #    stream_timeout: 1
  #    max_retries: 2
  #    rpm: 480

litellm_settings:
  log_raw_request_response: True
  drop_params: true
  add_function_to_prompt: true
  modify_params: true
  default_fallbacks: ["gpt-4"]
  #enable_json_schema_validation: true
  #fallbacks: [{"gpt-4": ["grklarge","grklarge2","grklarge3","grklarge4","mistral/mistral-large-2411","mistral/mistral-large-2402","mistral/mistral-large-2407","mistral/mistral-large-2411","groq/llama3-groq-70b-8192-tool-use-preview","groq/llama-3.3-70b-specdec","groq/llama3-groq-8b-8192-tool-use-preview","groq/llama-3.3-70b-versatile","groq/gemma2-9b-it","mmed","groq/llama-3.3-70b-versatile","groq/gemma2-9b-it","groq/open-mixtral-8x22b","openai/gpt-4o-mini","openai/gpt-4o-mini-2024-07-18","mixtral-8x7b-32768"]}, {"gpt-4o-mini": ["gpt-4o-mini-2024-07-18"]}, {"mmed": ["gpt-4o-mini-2024-07-18"]}, {"embedding": ["text-embedding-3-large","text-embedding-3-small","text-embedding-ada-002"]}, {"mistral/pixtral-12b-latest": ["vision","mistral/pixtral-12b-2409","groq/llama-3.2-11b-vision-preview","groq/llama-3.2-90b-vision-preview","gpt-4o-mini"]}, {"mmed": ["mistral/mistral-medium-2312","mistral/mistral-medium-2312","mistral/open-mixtral-8x22b","groq/llama-3.3-70b-specdec","gpt-4o-mini"]}, {"gpt-4": ["gpt-4"]}]
  #set_verbose: True  # Uncomment this if you want to see verbose logs; not recommended in production
  #max_budget: 99999
  #budget_duration: 30d
  #allowed_fails: 2 # cooldown model if it fails > 1 call in a minute. 
  #cooldown_time: 1 # how long to cooldown model if fails/min > allowed_fails
  #content_policy_fallbacks: [{"gpt-3.5-turbo-small": ["claude-opus"]}]
  #context_window_fallbacks: [{"gpt-4o": ["gpt-4o-mini"]}]
  #request_timeout: 4 # raise Timeout error if call takes longer than 10s. Sets litellm.request_timeout 
  #num_retries: 2
  telemetry: False
  retry: true
  cache_params:        # set cache params for redis
    type: redis
    namespace: "litellm_caching"
    user: os.environ/REDIS_USER
    host: os.environ/REDIS_HOST
    port: os.environ/REDIS_PORT
    password: os.environ/REDIS_PASSWORD
    #redis_url: os.environ/REDIS_URL


  #default_team_settings: 
  #  - team_id: team-1
      #success_callback: ["langfuse"]
      #failure_callback: ["langfuse"]
      #langfuse_public_key: os.environ/LANGFUSE_PROJECT1_PUBLIC # Project 1
      #langfuse_secret: os.environ/LANGFUSE_PROJECT1_SECRET # Project 1

# For /fine_tuning/jobs endpoints
#finetune_settings:
#  - custom_llm_provider: azure
#    api_base: https://exampleopenaiendpoint-production.up.railway.app
#    api_key: fake-key
#    api_version: "2023-03-15-preview"
#  - custom_llm_provider: openai
#    api_key: os.environ/LANGFUSE_PROJECT1_PUBLIC

# for /files endpoints
#files_settings:
#  - custom_llm_provider: azure
#    api_base: https://exampleopenaiendpoint-production.up.railway.app
#    api_key: fake-key
#    api_version: "2023-03-15-preview"
#  - custom_llm_provider: openai
#    api_key: os.environ/LANGFUSE_PROJECT1_PUBLIC

router_settings:
  routing_strategy: simple-shuffle # Literal["simple-shuffle", "least-busy", "usage-based-routing","latency-based-routing"], default="simple-shuffle"
  redis_host: os.environ/REDIS_HOST
  redis_user: os.environ/REDIS_USER
  redis_password: os.environ/REDIS_PASSWORD
  redis_port: os.environ/REDIS_PORT
  redis_url: os.environ/REDIS_URL
  enable_pre_call_checks: true
  model_group_alias: {"gpt-4": "gpt-4"} 

general_settings: 
  master_key: os.environ/LITELLM_MASTER_KEY # [OPTIONAL] Use to enforce auth on proxy. See - https://docs.litellm.ai/docs/proxy/virtual_keys
  #max_parallel_requests: 9  # the max parallel requests allowed per deployment 
  #global_max_parallel_requests: 33  # the max parallel requests allowed on the proxy all up 
  #proxy_budget_rescheduler_min_time: 60
  #proxy_budget_rescheduler_max_time: 64
  #proxy_batch_write_at: 1
  database_connection_pool_limit: 11
  store_model_in_db: os.environ/STORE_MODEL_IN_DB
  #database_url: os.environ/DATABASE_URL 
  #"postgresql://<user>:<password>@<host>:<port>/<dbname>" # [OPTIONAL] use for token-based auth to proxy
  pass_through_endpoints:
    - path: "/v1/rerank"                                  # route you want to add to LiteLLM Proxy Server
      target: "https://api.cohere.com/v1/rerank"          # URL this route should forward requests to
      headers:                                            # headers to forward to this URL
        content-type: application/json                    # (Optional) Extra Headers to pass to this endpoint 
        accept: application/json
      forward_headers: True

#environment_variables:
#  OPENAI_API_KEY: 
#  GROQ_API_KEY: 
#  GROQ_API_KEY2: 
#  GROQ_API_KEY3: 
#  GROQ_API_KEY4: 
#  MISTRAL_API_KEY: 
#  OPENROUTER_API_KEY:
#  OPENROUTER_API_KEY2:
#  OPENAI_BASE_URL:
#  GROQ_BASE_URL:
#  REDIS_HOST:
#  REDIS_PORT:
#  REDIS_PASSWORD: 
#  REDIS_USER:
